#!/usr/bin/env bash
set -e

function dateDdMmYyToIso {
    echo $(echo "$1" | sed 's|\([0-9]*\)-\([0-9]*\)-\([0-9]*\)|\3-\2-\1|')
}

if [[ "$EUID" -ne 0 ]]; then
    echo "This script must be run as root. Please use 'sudo'."
    exit 1
fi

backup_interval_days=10
DEBUG=yes

today=$(date -I)
target_directory="/storage"
destination_directory="/home/user/Backuper"
result="$destination_directory/$today.tar"

if [[ $DEBUG = "yes" ]]
then
    echo "today: $today"
    echo "target_directory: $target_directory"
    echo "destination_directory: $destination_directory"
    echo "result: $result"
fi

latest_backup=$(ls $destination_directory | grep .tar | tail -n 1)
if [[ ! "$latest_backup" = "" ]]
then
    latest_backup_date=${latest_backup%.tar}

    days_since_last_backup=$(( ($(date -d "$today" +%s) - $(date -d "$latest_backup_date" +%s)) / 86400 ))
    if (( days_since_last_backup <= 10 ))
    then
        echo "backup interval (days): $backup_interval_days"
        echo "the last backup was recently: $latest_backup"
        exit 0
    fi
fi

if [ -e $result ]; then
    echo "backup already exists: $result"
    exit 0
fi


echo "starting backup"
tar -cvf $result $target_directory

if [ -e $result ]; then
    echo "backup created: $result"
else
    echo "something went wrong: $result"
fi

